app:
  server:
    type: BRANCH_SERVICE
    id: branch-service-1

spring:
  application:
    name: branch service
  datasource:
    hikari:
      driver-class-name: org.h2.Driver
#      jdbc-url: 'jdbc:h2:mem:branch'
      jdbc-url: 'jdbc:h2:tcp://localhost/~/branch'
      username: branch
      password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show-sql: true
        format_sql: true
  grpc:
    server:
      port: 8083
  kafka:
    bootstrap-servers: localhost:10000,localhost:10001,localhost:10002

jwt:
  secret-key: "rYfed5F12iViHmbB7ZufrxIR6MNLG67+4+b6+DhqcRJuFVe7/KxhIb4necxKaCDN"
